export const openings = [
    'Všechno kolem působí, jako by se svět rozhodl na chvíli zpomalit, ale zapomněl ti to oznámit, protože',
    'Události mají tendenci tvářit se zásadně, i když ve skutečnosti jen zaplňují prostor, protože',
    'Atmosféra připomíná rozlité mléko – nic zásadního, ale přesto tě to donutí uklouznout, protože',
    'Občas se zdá, že bys měl něco podniknout, ale konkrétní instrukce vesmír neposlal, protože',
    'Hvězdy opatrně našlapují kolem tvé prokrastinace a tváří se, že nic nevidí, protože',
    'Vesmír si vede účet, ale ty jsi zapomněl, co jsi dlužil, protože',
    'Komunikační šumy se množí rychleji než nevyžádané rady, protože',
    'Normálnost je podezřelý jev, zvlášť když trvá déle než pět minut, protože',
    'Gravitace má dnes tendenci připomínat, že tvoje víčka mají vlastní vůli, protože',
    'Kosmické záření tě míjí s lhostejností, která by mohla být nakažlivá, protože',
    'Vše působí vlažně, jako instantní kaše bez chuti a zápachu, protože',
    'Hvězdné uspořádání připomíná nepořádek na pracovním stole, protože',
    'Tvůj horoskop se ztratil někde v překladu mezi realitou a očekáváním, protože',
    'Energie okolí je vhodná pro dlouhé zírání do zdi, případně do prázdna, protože',
    'Planety ti šeptají, abys zůstal v posteli, ale ekonomika má jiné plány, protože',
    'Nepříjemnosti si tě nacházejí s přesností pošťáka doručujícího složenky, protože',
    'Vesmír delegoval odpovědnost na náhodu a ty jsi toho výsledkem, protože',
    'Zapomínání na povinnosti je dnes povýšeno na umělecký výkon, protože',
    'Objevuješ v sobě touhu reorganizovat věci, které už dávno rezignovaly, protože',
    'Pocit, že ti něco uniká, je dnes jen další notifikací v záplavě jiných, protože',
    'Realita je rozostřená, jako by někdo vyměnil čočky za zamlžené brýle, protože',
    'Vibe pondělí se plíží i do dnů, které si to nezaslouží, protože',
    'Opatrnost při manipulaci s horkými nápoji je dnes vyšší forma moudrosti, protože',
    'Jsi hlavní postavou příběhu, který zůstává nevyprávěný, protože',
    'Známky a znamení přicházejí, ale jejich písmo je nečitelnější než tvůj rukopis, protože',
    'Kofein a existenciální úzkost tvoří harmonickou dvojku v pozadí dne, protože',
    'Charisma mokrého ručníku může být překvapivě atraktivní pro určité publikum, protože',
    'Mít pravdu je dnes luxus, který ti okolí nehodlá uznat, protože',
    'Neslibovat nic je dnes forma sebeobrany, ne lenosti, protože',
    'Mlhovina možností je hustá, výhled do budoucnosti zůstává zamlžený, protože',
    'Cítíš se jako beta verze sebe sama, plná bugů a nezdokumentovaných funkcí, protože',
    'Energie je neutrální, což je v tomto vesmíru vlastně malý zázrak, protože',
    'Setkání s realitou je dnes nevyhnutelné, i když bys raději zůstal v teorii, protože',
    'Trpělivost prochází testem, jehož výsledky zůstanou navždy utajeny, protože',
    'Sarkasmus má dnes silnější gravitační pole než Jupiter, protože',
    'Déjà vu je dnes běžnější než originální nápady, protože',
    'Den připomíná aktualizaci systému – nutný, zdlouhavý a nikdo ho nechtěl, protože',
    'Hvězdy mlčí, takže si budeš muset poradit sám, protože',
    'Nepochopení se dnes šíří rychleji než virální meme, protože',
    'Smysl pro humor je dnes jedinou povolenou měnou, protože',
    'Digitální detox zůstává v rovině teorie, stejně jako většina tvých plánů, protože',
    'Logika je dnes nedostatkovým zbožím, protože',
    'Bankovní účet je vhodné dnes neotvírat, stejně jako lednici po dovolené, protože',
    'Prokrastinace dosahuje nových výšin, téměř profesionální úrovně, protože',
    'Overthinkování drobností je dnes olympijskou disciplínou, protože',
    'Klacky pod nohy jsou spíš větvičky, ale i ty dokážou zamotat cestu, protože',
    'Instinkty mají dnes slabý signál, ale pizza z předvčerejška je stále riziko, protože',
    'Scénář mají všichni ostatní, ty improvizuješ s prázdnými stránkami, protože',
    'Odpovědí na otázky je dnes pouze „možná“, protože',
    'Prázdná stránka má dnes větší potenciál než tvůj to-do list, protože',
    'Existenciální krize je dnes povolena, ale jen v malých dávkách, protože',
    'Čas se vleče, jako by měl zpoždění na vlastní existenci, protože',
    'Memečka nabývají hlubších významů, pokud se na ně díváš dost dlouho, protože',
    'Dělat to, co jsi měl udělat už minulý týden, je dnes pokrok, protože',
    'Pocit nesprávného místa a času je běžný, zejména v obýváku, protože',
    'Brát věci osobně je dnes zbytečné, včetně tohoto textu, protože',
    'Všechno funguje, ale nikdo neví proč – stejně jako špatně napsaný kód, protože',
    'Analyzování nedůležitých věcí je dnes hlavní pracovní náplní, protože',
    'Vesmír se schovává a ty jsi ten, kdo počítá, protože',
    'Pasivní rezistence vůči povinnostem je dnes uznávanou strategií, protože',
    'Offline režim je dnes doporučen, ale nikdo se tím neřídí, protože',
    'Slepé uličky evoluce jsou dnes dobře značené, protože',
    'Dobrá nálada se dnes vydává pouze na příděl, protože',
    'Ignorovat idioty je dnes dovednost na úrovni černého pásu, protože',
    'Pocit, že jsi něco zapomněl, tě bude provázet jako tiché echo, protože',
    'E-maily je bezpečnější neotvírat, stejně jako staré deníky, protože',
    'Čekání na autobus, který nikdy nepřijede, je dnes metafora všeho, protože',
    'Konspirační teorie o vlastním životě dnes dávají až podezřele smysl, protože',
    'Signál vesmíru vypadl, zkuste to později, protože',
    'Být sám se sebou je dnes výzva pro pokročilé, protože',
    'Simulace má bugy, ale patch zatím není v plánu, protože'
];

export const tensions = [
    'rozhodnutí čekají na svou chvíli, ale netváří se, že by jim to vadilo.',
    'správný okamžik už dávno proběhl, ale nikdo ti neposlal pozvánku.',
    'snaha vnést řád často vede k novým variantám chaosu, což je v souladu s vesmírným plánem.',
    'reagovat na všechno je únavné, zejména když výzvy mají podobu spamové pošty.',
    'vnitřní hlas převádí vše do neznámého jazyka, překlad zatím není k dispozici.',
    'ignorovat realitu lze považovat za adaptivní strategii, alespoň na chvíli.',
    'to, co hledáš, se schovává přesně tam, kam bys nejraději nešel.',
    'seznam úkolů se ti vysmívá, ale s grácií zkušeného trolla.',
    'produktivita je dnes pouze slovo v motivačních příručkách.',
    'nejlepší řešení je někdy odložit problém do budoucnosti a doufat v zázrak.',
    'co nestihneš dnes, zítra tě najde v ještě horší náladě.',
    'snaha o dokonalost je roztomilá, ale výsledky jsou stejně rozmazané.',
    'některé věci je lepší nechat rozbité, alespoň tě nepřekvapí dalším selháním.',
    'odpověď na otázku je „ne“, ale tvá zvědavost to ignoruje.',
    'plán A selhal, plán B je v karanténě.',
    'chaos je jediný společník, který tě nikdy nenechá na holičkách.',
    'plavat proti proudu je náročné, zvlášť když řeka vyschla.',
    'intuice a strach dnes splývají do jednoho neidentifikovatelného pocitu.',
    'deadline je pouze doporučením, které nikdo nečte.',
    'ambice mají větší rozměr než tvé aktuální možnosti, což je běžné.',
    'když se něco nepovede, nejlepší je zamést stopy a tvářit se nenápadně.',
    'vliv na okolnosti je dnes iluzí, která se rychle rozplývá.',
    'komfortní zóna se zmenšuje úměrně s tvým nadšením.',
    'boj s větrnými mlýny je dnes vhodný pouze pro milovníky zbytečných aktivit.',
    'pravda bývá nepříjemná, lež je dnes pohodlnější volbou.',
    'priority se řadí podle abecedy, ne podle smyslu.',
    'pokud hledáš znamení, že máš přestat, právě jsi ho našel.',
    'úspěch se dnes měří tím, že jsi stále tady.',
    'krok zpět je někdy jediný pohyb, který má smysl.',
    'očekávání jsou hlavním zdrojem zklamání, což je paradoxně očekávatelné.',
    'odkládat věci na zítřek je investice do budoucího zklamání.',
    'snažit se zalíbit je jako házet perly do prázdné místnosti.',
    'vnitřní kritik má dnes vlastní rozhlasové vysílání.',
    'cesta nejmenšího odporu je momentálně jediná průchozí.',
    'pokud něco funguje, je lepší do toho nezasahovat. Pokud nefunguje, platí totéž.',
    'paměť je dnes selektivní, vybírá si, co tě má zaskočit.',
    'hrdinské činy lze dnes nahradit prostým přežitím.',
    'odkládané věci se množí, i když na ně nemyslíš.',
    'vůle je dnes stejně pevná jako mokrý papír.',
    'obrana je někdy lepší v podobě ústupu než útoku.',
    'mít pocit kontroly je dnes pouze dočasná iluze.',
    'chyby se dnes promění buď v lekce, nebo v další chyby.',
    'vzdát se není ostuda, někdy je to nejlepší volba.',
    'optimismus dnes postrádá oporu v realitě, což mu nebrání v existenci.',
    'realita tě dožene, i když se budeš snažit utéct.',
    'to, co chceš slyšet, zůstane nevyslovené.',
    'trpělivost je testována, výsledek není důležitý.',
    'přiznat „nevím“ je dnes známka moudrosti.',
    'na omluvu můžeš čekat, ale doporučuje se mezitím žít dál.',
    'snaha o originalitu končí v katalogu klišé.',
    'nechat věci plynout je v pořádku, i když směr není zrovna ideální.',
    'kompromis dnes bolí všechny zúčastněné rovnoměrně.',
    'pokud se cítíš ztraceně, možná je čas přestat hledat mapu.',
    'logika dnes ztrácí body v souboji s emocemi.',
    'vítězem je ten, kdo se rozhodne nezúčastnit.',
    'to, co považuješ za konec, je pouze úvod do nové série problémů.',
    'zvědavost dnes zabíjí nejen kočky, ale i tvůj čas.',
    'pokud něco vypadá příliš dobře, je to pravděpodobně past na důvěřivce.',
    'diplomacie je dnes nedostatkové zboží, improvizace vítězí.',
    'upřímnost ti přinese jen nové komplikace, ale aspoň budeš mít o čem přemýšlet.',
    'nejlepší rada je ta, kterou stejně ignoruješ.',
    'když ti nikdo nerozumí, možná mluvíš v příliš komplikovaných metaforách.',
    'vítězství má dnes pachuť kompromisu.',
    'kontrola je dnes pouze dočasná funkce, která se často restartuje.',
    'rozhodnutí vede k lítosti, nerozhodnost k frustraci. Vyber si.',
    'vyhrát není cílem, hlavní je neprohrát příliš okatě.',
    'energie by se dala využít lépe, ale dnes na to není prostor.',
    'hledání viníka vede neomylně k zrcadlu.',
    'druhé šance jsou dnes pouze teoretickou možností.',
    'víra v lidstvo je dnes vystavena zkoušce, kterou málokdo složí.',
    'sebedůvěra je dnes riziková investice.',
    'maraton bez bot je dnes přesná metafora tvého nasazení.',
    'kreativita je zablokovaná, ale alespoň máš čas na jiné výmluvy.',
    'na zázrak čekáš na špatném nádraží, vlaky nejezdí.',
    'limity se dnes ukazují s nečekanou jasností.',
    'odvaha a hloupost dnes splývají v jedno.',
    'nelíbí-li se ti stav věcí, změna je možná, ale bůčo je jistější.',
    'lekce pokory přichází bez varování.',
    'intuice dnes podává zkreslené informace.',
    'dno má sklep, pokud jsi to ještě nezjistil.',
    'přežít je dnes vítězství, rozkvět je na pořadí zítřka.',
    'být milý je dnes riziková disciplína.',
    'spravedlnost je dnes na dovolené na jiné planetě.',
    'staré chyby se připomínají, i když bys je raději nechal spát.',
    'paměť má dnes děravé dno.',
    'nenahraditelnost je mýtus, voda v kýblu to dokazuje.',
    'nervy jsou dnes testovány na maximální zátěž.',
    'efektivita vede k chybám, neefektivita k frustraci.',
    'potlesk se dnes nekoná, ale ticho má také své kouzlo.',
    'den nedaruje nic, ale bere s elegancí.',
    'sebedůvěra je křehká, stejně jako tvoje ranní káva.',
    'jistota ve vlastním počínání je dnes podezřelá.',
    'překážky jsou dnes tvým vlastním dílem, což je dobrá i špatná zpráva.',
    'snaha o změnu narazí na odpor, často tvůj vlastní.',
    'klid je dnes luxus, který si nepořídíš.',
    'chaos tě vítá jako svého dávného známého.',
    'naděje bloudí bez mapy.',
    'to nejhorší může být teprve před tebou, ale neboj, možná si toho ani nevšimneš.',
    'další cihla ve zdi, další den ve frontě na smysl.',
    'snaha o pochopení připomíná běh hlavou proti zdi.'
];

export const karmas = [
    'Tvá karma je mírně poškrábaná. Ale neboj, škrábance dodávají charakter.',
    'Tvá karma je v režimu letadlo. Nikdo se ti dnes nedovolá, ani osud.',
    'Tvá karma potřebuje restart. Bohužel tlačítko je zamčené pod administrátorským heslem.',
    'Tvá karma je čistá, ale jen proto, že ji nikdo dlouho nepoužil.',
    'Tvá karma je ve slevě. Kvalita zůstává, jen očekávání klesá.',
    'Tvá karma je nedostupná. Zkus později, nebo nikdy.',
    'Tvá karma je na dovolené. Zastupuje ji automatická odpověď.',
    'Tvá karma je v mínusu. Ale pořád máš kredit u vesmíru.',
    'Tvá karma je v plusu, ale jen o kousek. S velkým úsilím to půjde do nuly.',
    'Tvá karma je neutrální. Což je v tomto světě vlastně maximum.',
    'Tvá karma je jako počasí v dubnu. Nikdo neví, co přijde, ani meteorolog.',
    'Tvá karma je jako wifi v metru. Občas zabliká, ale většinou tě nechá čekat.',
    'Tvá karma je jako pondělní ráno. Nikdo ji nemá rád, ale všichni ji musí přežít.',
    'Tvá karma je jako páteční odpoledne. Všichni už myslí na něco jiného.',
    'Tvá karma je jako nedělní večer. Zní to melancholicky a je v tom kus pravdy.',
    'Tvá karma je jako studená káva. Očekávání byla vyšší.',
    'Tvá karma je jako teplé pivo. Nikdo to dobrovolně nechce, ale někdy není na výběr.',
    'Tvá karma je jako vybitý mobil. Potenciál tu je, ale energie chybí.',
    'Tvá karma je jako zapomenuté heslo. Možná ji někdo jednou obnoví.',
    'Tvá karma je jako ztracené klíče. Hledáš ji v místech, kde nikdy nebyla.',
    'Tvá karma je jako rozvázaná tkanička. Vypadá nevinně, ale může tě srazit.',
    'Tvá karma je jako zaseknutý zip. Snažíš se, ale výsledek je pochybný.',
    'Tvá karma je jako vrzající dveře. Upozorní na sebe v nejméně vhodnou chvíli.',
    'Tvá karma je jako kapající kohoutek. Nenápadně tě připravuje o nervy.',
    'Tvá karma je jako prasklá žárovka. Světlo na konci tunelu je v nedohlednu.',
    'Tvá karma je jako vypsaná propiska. Vypadá funkčně, ale nic z ní nedostaneš.',
    'Tvá karma je jako zmačkaný papír. Dá se ještě použít, ale už to není ono.',
    'Tvá karma je jako rozlitá voda. Nejprve tě rozčílí, pak ji vytřeš.',
    'Tvá karma je jako mastný displej. Vidíš v ní otisky minulosti.',
    'Tvá karma je jako zamotaná sluchátka. Každý pokus o rozmotání vše jen zhorší.',
    'Tvá karma je jako pomalá Wi-Fi. Odezva je, ale až když už ji nepotřebuješ.',
    'Tvá karma je jako aktualizace Windows. Přijde vždy v nejhorší možný čas.',
    'Tvá karma je jako spam v mailu. Nikdo ji nechtěl, ale je jí plná schránka.',
    'Tvá karma je jako reklama na YouTube. Přeskočit nejde.',
    'Tvá karma je jako vybitá baterie. Potřebuješ ji, když už nic jiného nemáš.',
    'Tvá karma je jako ztracená ponožka. Nikdy nebude párová.',
    'Tvá karma je jako nenalezený soubor. Systém hlásí chybu, ale nikdo neví proč.',
    'Tvá karma je jako nekonečný scroll. Pořád pokračuješ, ale nikdy nenajdeš konec.',
    'Tvá karma je jako studený čaj. Vypiješ ji, protože je to škoda vylít.',
    'Tvá karma je jako modrá obrazovka. Zastaví tě ve chvíli, kdy to nejméně čekáš.',
    'Tvá karma je jako prázdná lednice. Možnosti jsou omezené, ale naděje neumírá.',
    'Tvá karma je jako nedopsaná zpráva. Zůstává viset ve vzduchu.',
    'Tvá karma je jako kočka Schrödingerova. Je současně dobrá i špatná, dokud se na ni nepodíváš.',
    'Tvá karma je jako 404 Not Found. Smysl nenalezen.',
    'Tvá karma je jako pátek třináctého. Můžeš věřit na smůlu, nebo na náhodu.',
    'Tvá karma je jako retrográdní Merkur. Všichni o ní mluví, nikdo jí nerozumí.',
    'Tvá karma je jako špatně zapnutý knoflík. Něco nehraje, ale přijdeš na to pozdě.',
    'Tvá karma je jako připálený toast. Snídaně i den začínají poněkud hořce.',
    'Tvá karma je jako ubrečené dítě. Ignorovat ji nejde, ale řešení je v nedohlednu.',
    'Tvá karma je jako štěkající pes. Hlučná, ale většinou neškodná.',
    'Tvá karma je jako hlučný soused. Připomíná se, když chceš mít klid.',
    'Tvá karma je jako vrtání do zdi. Zní hůř, než ve skutečnosti je.',
    'Tvá karma je jako ucpaný odpad. Proudí jen to, co bys raději neviděl.',
    'Tvá karma je jako rozbitý deštník. Slibuje ochranu, ale promokneš stejně.',
    'Tvá karma je jako děravá kapsa. Věci mizí, aniž by sis toho všiml.',
    'Tvá karma je jako špinavé brýle. Všechno vypadá horší, než ve skutečnosti je.',
    'Tvá karma je jako rozmazaný text. Snažíš se číst mezi řádky, ale stejně to nedává smysl.',
    'Tvá karma je jako chybějící dílek. Nic není úplné, ale život běží dál.',
    'Tvá karma je jako křivý obraz. Všichni to vidí, jen ty ne.',
    'Tvá karma je jako uschlá kytka. Bývala krásná, ale pořád ji nechceš vyhodit.',
    'Tvá karma je jako prázdná role. Nečekaně ti dojde v nejhorší chvíli.',
    'Tvá karma je jako zaseknutý papír. Zůstaneš v tiskárně života.',
    'Tvá karma je jako modřina na holeni. Bolí, i když na ni nemyslíš.',
    'Tvá karma je jako tříska v prstu. Malá, ale připomíná se s každým pohybem.',
    'Tvá karma je jako kousnutí do jazyka. Nečekané a zbytečně bolestivé.',
    'Tvá karma je jako škytavka. Přijde, když ji nejméně potřebuješ, a zmizí bez varování.',
    'Tvá karma je jako mravenčení v noze. Nepříjemná, ale přejde.',
    'Tvá karma je jako zalehlé ucho. Slyšíš, ale všechno je tlumené.',
    'Tvá karma je jako rýma. Otravuje, ale není důvod k panice.',
    'Tvá karma je jako kašel. Upozorní na sebe, i když nechceš.',
    'Tvá karma je jako kýchání. Přijde neohlášeně a odejde bez rozloučení.',
    'Tvá karma je jako svědění. Čím víc ji ignoruješ, tím víc se připomíná.',
    'Tvá karma je jako ospalost. Nevyhneš se jí, i když bys chtěl.',
    'Tvá karma je jako hlad. Dá o sobě vědět, když je to nejméně vhodné.',
    'Tvá karma je jako žízeň. Je těžké ji utišit, když není po ruce řešení.',
    'Tvá karma je jako nuda. Přichází nepozvaná a zůstává déle, než bys chtěl.',
    'Tvá karma je jako trapné ticho. Každý ho zažil, málokdo si ho užil.',
    'Tvá karma je jako špatný vtip. Někdo se zasměje, ale většina jen protočí oči.',
    'Tvá karma je jako falešný úsměv. Vypadá dobře jen na fotkách.',
    'Tvá karma je jako studené ruce. Zahřeješ je jen vlastním úsilím.',
    'Tvá karma je jako mokré ponožky. Nepříjemná, ale přežít se to dá.',
    'Tvá karma je jako kamínek v botě. Malá překážka, která tě donutí přemýšlet o smyslu života.',
    'Tvá karma je jako vlas v jídle. Zkazí ti chuť, ale přežiješ to.',
    'Tvá karma je jako moucha v pokoji. Nedá ti pokoj, dokud ji nevyženeš.',
    'Tvá karma je jako komár u ucha. Malá, ale neignorovatelná.',
    'Tvá karma je jako pavouk na stěně. Většinu času jen pozoruje, ale někdy tě překvapí.',
    'Tvá karma je jako prach na polici. Hromadí se, i když se snažíš uklízet.',
    'Tvá karma je jako šmouha na okně. Zmizí, když přestaneš hledat dokonalost.',
    'Tvá karma je jako skvrna na tričku. Vždycky se objeví, když to nejméně čekáš.',
    'Tvá karma je jako díra v punčoše. Neplánovaná, ale nezastaví tě.',
    'Tvá karma je jako utržený knoflík. Drží pohromadě silou zvyku.',
    'Tvá karma je jako zlomený nehet. Nepříjemné, ale ne fatální.',
    'Tvá karma je jako odřený loket. Malá bolest, která připomíná, že žiješ.',
    'Tvá karma je jako spálený jazyk. Chvíli bolí, pak se zapomene.',
    'Tvá karma je jako zmrzlý mozek. Všechno se na chvíli zastaví.',
    'Tvá karma je jako husí kůže. Přichází s nečekanými impulzy.',
    'Tvá karma je jako studený pot. Zjeví se bez varování, zmizí bez rozloučení.',
    'Tvá karma je jako noční můra. Ráno se rozplyne, ale pocit zůstává.',
    'Tvá karma je jako nespavost. Čím víc na ni myslíš, tím déle trvá.',
    'Tvá karma je jako budík. Ozve se, když to nejméně potřebuješ.',
    'Tvá karma je jako pondělí. Nikdo ji nechce, ale je nevyhnutelná.',
    'Tvá karma je jako daně. Vyhnout se jí můžeš jen krátkodobě.',
    'Tvá karma je jako složenky. Přichází pravidelně a neptá se, jestli máš náladu.',
    'Tvá karma je jako fronta na poště. Všichni tam musí, nikdo tam nechce.',
    'Tvá karma je jako dopravní zácpa. Posuneš se vpřed, až když to vzdáš.',
    'Tvá karma je jako červená na semaforu. Stojíš, i když bys nejraději běžel.',
    'Tvá karma je jako objížďka. Zkomplikuje cestu, ale někdy ukáže nové výhledy.',
    'Tvá karma je jako výluka. Plány se mění, ale cíle zůstávají stejné.',
    'Tvá karma je jako revizor. Přijde, když to nejméně čekáš a vždy něco najde.',
    'Tvá karma je jako pokuta. Zaplatíš, i když nevíš za co.',
    'Tvá karma je jako upomínka. Připomene se, i když ji nechceš slyšet.',
    'Tvá karma je jako exekuce. Přijde, když už jsi všechno ostatní přehlédl.',
    'Tvá karma je jako bankrot. Když už není co ztratit, můžeš jen získat.'
];

export const metas = [
    'Smysl lze hledat, ale jeho nalezení nezaručuje spokojenost. Tento text je vhodný pouze pro čtenáře s vysokou tolerancí k absurditě.',
    'Výklad platí pouze do chvíle, než se nad ním začneš příliš zamýšlet. Pak už je to čistě tvoje odpovědnost.',
    'To, že ti něco z toho připadá povědomé, je spíš náhoda než znamení. Hadonoš nenese odpovědnost za tvé existenciální otázky.',
    'Autor tohoto sdělení si není jistý, zda má pravdu, ale to mu nikdy nebránilo v publikování.',
    'Aktualizace osudu proběhne bez předchozího upozornění. Reklamace přijímáme pouze ve snu.',
    'Vesmír o tomto horoskopu nemá žádné záznamy. Všechno ostatní je jen domněnka.',
    'Pokud se ti horoskop nelíbí, obrať se na správce simulace. Odpověď očekávej v příštím životě.',
    'Hvězdy nenesou odpovědnost za rozhodnutí, která na jejich základě učiníš. Ani tento text.',
    'Tento výklad je sponzorován náhodou a schválen chaosem. Všechny podobnosti jsou čistě záměrné.',
    'Horoskop neobsahuje lepek, stopy oříšků ani žádná řešení tvých problémů.',
    'Platnost výkladu je omezena na tuto časovou linii. V paralelních vesmírech se může lišit.',
    'Po přečtení se horoskop sám nezničí, což je škoda pro ekologii i tvoji duši.',
    'Všechny postavy a události jsou smyšlené, včetně těch, které se ti zdají povědomé.',
    'Ministerstvo zbytečných věcí doporučuje číst s nadhledem. Nebo vůbec.',
    'Hledání znamení je povoleno, ale výsledek není garantován. Tento text není výjimkou.',
    'Chyba 404: Smysl života nenalezen. Pokračuj ve čtení na vlastní riziko.',
    'Horoskop je pouze placeholder pro skutečný osud, který je momentálně nedostupný.',
    'Ekologicky recyklujeme staré pravdy. Pokud jsi je slyšel už dřív, ber to jako upcyklaci.',
    'Tento text je chráněn autorským právem vesmíru, ale kopírovat můžeš dle libosti.',
    'Kompatibilita s tvou neurózou není zaručena. Případné vedlejší účinky konzultuj s realitou.',
    'Načítání osudu se může kdykoli zaseknout. Restart je na vlastní nebezpečí.',
    'Horoskop je zdarma, a přesto předražený. Vstupné platíš svým časem.',
    'Vše je jen shluk pixelů na displeji. Zbytek je práce tvé představivosti.',
    'Upozornění: Tento text může obsahovat stopy sarkasmu, ironie a reziduálního smutku.',
    'Horoskop je jako čínský koláček štěstí, jen bez koláčku a bez štěstí.',
    'Výklad byl vygenerován v temné hmotě. Pokud mu nerozumíš, jsi na správné cestě.',
    'Tento text nebyl testován na lidech. Výsledky jsou čistě experimentální.',
    'Platnost výkladu může vypršet bez předchozího upozornění. Skladujte v chladu a temnu.',
    'Osud byl vygenerován bez znalosti kontextu. Pokud se trefil, je to náhoda.',
    'Vesmír odmítl komentovat obsah tohoto sdělení. Všechno ostatní je spekulace.',
    'Tento horoskop není investiční doporučení. Ani životní.',
    'Výklad byl schválen algoritmem, který ničemu nerozumí. Stejně jako většina lidí.',
    'Smysl je pouze vedlejším produktem náhody. Pokud ho najdeš, gratulujeme.',
    'Pokračování ve čtení je na vlastní odpovědnost. Doporučujeme přimhouřit obě oči.',
    'Horoskop ignoruje tvé minulé chyby. Bohužel, ty je budeš muset řešit sám.',
    'Tento výklad vznikl v prostředí s nízkou gravitací reality.',
    'Vesmír dnes použil záložní plán. Nikdo neví, co to znamená.',
    'Kompatibilita s tvou aktuální verzí osobnosti není ověřena.',
    'Význam tohoto sdělení se může měnit v závislosti na náladě čtenáře.',
    'Text byl doručen se zpožděním, které je v existenci běžné.',
    'Výklad byl vytvořen v režimu úspory energie. Pokud je stručný, je to záměr.',
    'Vesmír dnes odpovídá pouze automatickou zprávou.',
    'Tento text prošel pouze minimální kontrolou kvality. Možné chyby jsou součástí zážitku.',
    'Osud je pouze orientační. Finální rozhodnutí je na tobě, což je ta horší varianta.',
    'Výklad je platný, dokud o něm nepřemýšlíš. Pak už je pozdě.',
    'Tento horoskop neřeší příčiny, pouze následky. A to ještě s rezervou.',
    'Výklad je výsledkem kompromisu mezi chaosem a leností.',
    'Smysl dne byl přesunut na později. Zatím si vystač s tímto textem.',
    'Text vznikl bez ohledu na tvé plány. Pokud se trefuje, je to čistá náhoda.',
    'Horoskop je optimalizován pro nejhorší možný scénář. Pokud je ti líp, je to bonus.',
    'Vesmír dnes použil generický text. Personalizace je na tobě.',
    'Osud je pouze návrh, jeho schválení je ve tvých rukou.',
    'Výklad ignoruje všechny relevantní proměnné. To není chyba, ale vlastnost.',
    'Tento text není závazný ani pro vesmír, ani pro tebe.',
    'Korekturu reality si musíš udělat sám. Tento text ji neobsahuje.',
    'Výklad vznikl jako vedlejší produkt něčeho důležitějšího.',
    'Vesmír testuje, kolik toho sneseš. Zatím to zvládáš.',
    'Horoskop je složen z dostupných fragmentů. Pokud něco chybí, je to záměr.',
    'Smysl může být přítomen, ale jeho výskyt není zaručen.',
    'Osud je v beta verzi. Opravy chyb budou oznámeny později.',
    'Výklad byl schválen komisí, která se nikdy nesešla.',
    'Text není určen k hlubší analýze, ale stejně ji provedeš.',
    'Vesmír dnes odpovídá vyhýbavě. Zkus to zítra.',
    'Tento text je platný pouze pro tuto iteraci. V další už budeš někdo jiný.',
    'Výklad nebere v potaz realitu. Pokud se shoduje, je to náhoda.',
    'Smysl byl odstraněn kvůli kompatibilitě s běžným životem.',
    'Horoskop vznikl bez záměru, což je jeho hlavní přednost.',
    'Vesmír pracuje s omezenými zdroji. Toto je maximum, co můžeš dnes dostat.',
    'Tento text je důsledkem entropie, nikoli inspirace.',
    'Osud je jen statistická odchylka. Zbytek je rutina.',
    'Výklad byl generován bez empatie. Pokud tě potěšil, je to chyba v matrixu.',
    'Horoskop je orientační bod v mlze. Směr si musíš určit sám.',
    'Vesmír dnes neposkytuje podporu. Zkuste to později.',
    'Toto je konečná verze textu. Nebo taky ne, záleží na algoritmu.',
    'Výklad je výsledkem špatného odhadu. Pokud ti dává smysl, gratuluji.',
    'Smysl se může dostavit se zpožděním, případně vůbec.',
    'Osud byl vybrán náhodně, stejně jako většina důležitých věcí.',
    'Vesmír dnes nepřebírá odpovědnost. Všechno ostatní je na tobě.'
];

export const symbols = [
    'Kávová lžička', 'Ztracená ponožka', 'Vybitá baterie', 'Nenalezený soubor',
    'Nekonečný scroll', 'Studený čaj', 'Zapomenuté heslo', 'Modrá obrazovka',
    'Prázdná lednice', 'Nedopsaná zpráva', 'Kočka Schrödingerova', '404 Not Found',
    'Pátek třináctého', 'Retrográdní Merkur', 'Špatně zapnutý knoflík',
    'Rozvázaná tkanička', 'Připálený toast', 'Zaseknutý zip', 'Vrzající dveře',
    'Kapající kohoutek', 'Prasklá žárovka', 'Vypsaná propiska', 'Zmačkaný papír',
    'Rozlitá voda', 'Mastný displej', 'Zamotaná sluchátka', 'Pomalá Wi-Fi',
    'Aktualizace Windows', 'Spam v mailu', 'Reklama na YouTube', 'Vybitý mobil',
    'Ztracené klíče', 'Zapomenutá peněženka', 'Prošlý jogurt', 'Tvrdý chleba',
    'Studená sprcha', 'Zpožděný vlak', 'Plný autobus', 'Ubrečené dítě',
    'Štěkající pes', 'Hlučný soused', 'Vrtání do zdi', 'Ucpaný odpad',
    'Rozbitý deštník', 'Děravá kapsa', 'Špinavé brýle', 'Rozmazaný text',
    'Chybějící dílek', 'Křivý obraz', 'Uschlá kytka', 'Prázdná role',
    'Zaseknutý papír', 'Modřina na holeni', 'Tříska v prstu', 'Kousnutí do jazyka',
    'Škytavka', 'Mravenčení v noze', 'Zalehlé ucho', 'Rýma',
    'Kašel', 'Kýchání', 'Svědění', 'Ospalost',
    'Hlad', 'Žízeň', 'Nuda', 'Trapné ticho',
    'Špatný vtip', 'Falešný úsměv', 'Studené ruce', 'Mokré ponožky',
    'Kamínek v botě', 'Vlas v jídle', 'Moucha v pokoji', 'Komár u ucha',
    'Pavouk na stěně', 'Prach na polici', 'Šmouha na okně', 'Skvrna na tričku',
    'Díra v punčoše', 'Utržený knoflík', 'Zlomený nehet', 'Odřený loket',
    'Spálený jazyk', 'Zmrzlý mozek', 'Husí kůže', 'Studený pot',
    'Noční můra', 'Nespavost', 'Budík', 'Pondělí',
    'Daně', 'Složenky', 'Fronta na poště', 'Dopravní zácpa',
    'Červená na semaforu', 'Objížďka', 'Výluka', 'Revizor',
    'Pokuta', 'Upomínka', 'Exekuce', 'Bankrot'
];
